### ISSUE TITLE
Material Replacer Conflict with D4rkAvatarOptimizer

### ISSUE THREAD

**Issue by Kare-Udon** [lilxyzw/lilycalInventory#101]
Sorry for using English. I appreciate your work so much! I it so convenient.

### Environment

- Test Avatar: Manuka (Directly from Prefeb, no modification)
- Unity Version: 2022.3.22f1
- lilycalIventory Version: 1.1.0
- D4rkAvartarOptimizer Version: 3.8.0

### Problem

I am trying to replace the material of Manaka's body (including face and body), but it just didn't work and there is no error log.

But when I try to replace the material of clothes or other stuff, it works fine.

### What I have done

- Add a Li Prop for toggle material
- Add Manuka's body and head Mesh Render to Li Prop
- Add some material for replacing

When using "Preview" of Li Prop, material replacement looks fine, but after entered Play mode, it doesn't work.

### What I tested

By removing D4rkAvatarOptimizer, Material Replacer works fine.

I knew D4rkAvartarOptimizer often causes conflicts due to its aggressive Avatar optimizing, but it really makes my Avatar's performance 
much better. 

As it is totally not your fault, you can go ahead for new features first, and lower the priority of the restoration, or just ignore it, it is totally fine.

Thank you for your work again!

### Images

![image](https://github.com/user-attachments/assets/69e525c0-dd7f-49ce-b580-5707bea69efb)

**Comment by Kare-Udon** [comment]
Further test:
I have also tested on Karin, it also appears that the material of body can't be changed when D4rkAvatarOptimizer is installed, but clothes can.

**Comment by lilxyzw** [comment]
I have identified the cause and created an issue. [#121](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/121)
However, I will also fix it on the lilycalInventory side in case the same problem occurs with tools other than d4rkAvatarOptimizer.
