### ISSUE TITLE
[Feature] @ SmoothChanger - "[x] Apply to all renderers" global setting

### ISSUE THREAD

**Issue by Martin-H2** [lilxyzw/lilycalInventory#105]
Hello dear person. I really like your awesome lilycalInventory util ! 

I have one suggestion though, that would:
- save a LOT of work when creating many keyframes for all renderers
- makes sliders portable between all avis when doing general purpose settings (e.g. min/brightness, saturation, HSL slider for theme colors etc)

Can you please add a setting to apply SmoothChanger key-frames to ALL renders found on the avatar (just like VRCFurry does it). Either by providing a global checkbox "[x] Apply to all renderers" - or by leaving the "Mesh and Renderer" list empty ?
Checkbox solution would be cleaner though, and then the "Mesh and Renderer" lists can be hidden below in all keyframes.

Greetings <3

**Comment by lilxyzw** [comment]
Is this it...?
> If nothing is specified, all meshes will be controlled.
![image](https://github.com/user-attachments/assets/336e6d58-178d-4427-88f0-4cdd7195b4ae)

**Comment by lilxyzw** [comment]
Oops, I forgot to write that...💦 I will add.
