### ISSUE TITLE
ItemToggler/Propにおいて、初期状態に戻すためのメニューを生やすオプションがあると良い可能性がある?

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#106]
例えば、状態A(デフォルト)と状態Bがあるとして、これを当該コンポーネントを使って切り替えることを考えます。
そうすると、今は状態Bのメニュー項目だけが生成され、状態AはそのメニューをOFFにすることで切り替えることになります。

ここで、状態Aと状態Bのメニュー項目を両方生やせると嬉しいケースがあるかもしれないと思いました。
(物のオンオフなら片方あれば十分で、両方は冗長ですが、物の入れ替えやマテリアルの差し替えであれば両方のメニューがある方が分かりやすいことがあります。)
現状でそれを実現するためにはCostumeChangerかAutoDresserが必要になりますが、2択の切り替えのためにそれを使うのは少し冗長にも感じられます。

ただし、設定項目が増えるとUIが分かりづらくなる恐れがあります。
分かりづらくなりそうであれば、そこまでして追加するものでもないのかな…?と思います。良ければご一考ください。

**Comment by lilxyzw** [comment]
複数メニューを生成する場合はCostumeChangerを使うように統一する方向で行きます。現状CostumeChangerはintパラメーターで8bit消費しますが、n-bit intの要望が多いためもし実装されれば問題を解決できる可能性はあります。
