### ISSUE TITLE
[Feature] Integer Multi Switch

### ISSUE THREAD

**Issue by Martin-H2** [lilxyzw/lilycalInventory#107]
Hello,
it would be very nice to have a "Multi switcher" for the integer type that allows you to:
- define the Integer param that should be used
- define the "pressed" value
- toggle meshes / blendshapes / materials etc as usual 

I guess maybe the Autodresser is something similar like this ? But Autodresser does not give control over the parameter and the "pressed" value. Also "Multi switcher" is meant to be used for just anything. Switching between a set of materials / variants etc of something or between multiple chokers / hats etc

**Comment by lilxyzw** [comment]
`LI Preset` added in version 1.1.0 might be what you're looking for. They allow you to set any component property to any value.
![image](https://github.com/user-attachments/assets/efb6d4f5-6cdb-42a3-94fc-bac4e9d4d594)
