### ISSUE TITLE
How is "Preview Always" work?

### ISSUE THREAD

**Issue by Yueby** [lilxyzw/lilycalInventory#109]
![image](https://github.com/user-attachments/assets/bfa6ae46-a4d1-4c23-a711-f117e0ebda68)
I select "Preview Always" and it work well when i keep lilinventory component inspector window, but when inspector window close or select other gameObject, preview will reset to default.
So i want to figure out what the different between "Preview" and "Preview Always"?

**Comment by Yueby** [comment]
Ah I understand, “Preview Always” it can auto preview when select lilinventory component again.
If it possible to save preview parameters to avatar? Sometimes I want to keep some preview to default.

**Comment by lilxyzw** [comment]
No, the component preview is the same as the AnimationClip preview and is not saved in the avatar. It is just the apparent values ​​that change.
