### ISSUE TITLE
Preview slider values are static field?

### ISSUE THREAD

**Issue by Yueby** [lilxyzw/lilycalInventory#111]
I noticeed preview slider value like a static field, not a single component field.
When I change slider value and select other costume object, the slider value was same.
![image](https://github.com/user-attachments/assets/0a94ae49-7e04-463b-b4f8-6ea52a56be49)

**Comment by lilxyzw** [comment]
Yes, the preview is always managed by a single object to prevent it from being corrupted.
https://github.com/lilxyzw/lilycalInventory/blob/main/Editor/Helper/PreviewHelper.cs
