### ISSUE TITLE
One Item Toggle Component enable and make another  Item Toggle Component  disabled

### ISSUE THREAD

**Issue by milkboy77** [lilxyzw/lilycalInventory#112]
For example:
I have three furry rabbits of the same size in the same position, and I want to use Item Toggle to open these rabbits.
When I open the first rabbit using the Item Toggle Component, everything works as expected.
But when I try to open the second rabbit in the same way, the first Item Toggle Component is not closed, which causes the first rabbit and the second rabbit to overlap.

I tried turning off the other two rabbits in Cpmponent, but all three options of the menu are enabled at the same time.

That is, the menu only shows the corresponding rabbit when one is enabled.

I'm not quite sure what Item Prop as well as Item Preset does.

But I don't want to use Costume Changer Component or SmoothChanger Component, they both take up 8 Parameters, and I only need 3 rabbit ornaments, the most economical way is to use 3 Bools, and the 3 Bools can be controlled each other by the State and the The most economical way is to use three Bools, and the three Bools can be controlled by State and Parameter Driver. The most economical way is to use three Bools, and the three Bools can be controlled by State and Parameter Driver before.
![image](https://github.com/user-attachments/assets/0dfc3997-e6fa-4c2b-90a6-b528010adc90)

**Comment by lilxyzw** [comment]
The issue is due to ints always using 8-bit parameters, so this may be implemented in the future as compression of int parameters.
