### ISSUE TITLE
LI MenuFolder等のパス指定と既存のsub menuが一致している時の取り合い

### ISSUE THREAD

**Issue by Uttu209** [lilxyzw/lilycalInventory#119]
LI MenuFolderなどでパス入力しつつmenuを作れるようになりましたが、
例えばすでにルート下にPSettingsというsub menuが存在しているときに
LI MenuFolderで"PSettings/DW5/Bag"
などとすると、既存のPSettingsと別にPSettingsがsub menuとして現れました。
同じ名前のsub menuがすでに存在する場合はそれを使ってくれるとうれしいかなと思います。

**Comment by lilxyzw** [comment]
既存のメニューと統合する処理は1.2.0にて追加されました。
もし統合したいメニューが他のツールによってlilycalInventotyの処理よりあとに生成される場合、そのツールがメニューの統合処理をする必要があります。

**Comment by Uttu209** [comment]
お返事でMAが統合してくれないという事がわかったのと、マニュアルを再読してもうちょっと理解を深めよう…、と思ってVRCFury風に全てパスで入力するのを諦めつつ別の方法を色々試した結果、
画像のようにすればなんとか理想的な状態にできました。
ですが辿り着くまで少し時間がかかったので
LI MenuFolderを重ねたときは自動で子の方に"メニューの親フォルダ"がセットされるか、
親側のLI MenuFolderのinspector内で、入れ子にしたMenu Folderを子のフォルダにすることを設定出来るとうれしいかもです。(子のFolderにメニューの親フォルダをセットしていなくても、"フォルダの中身"に入ってるのですぐに気がつかなかった)

などと書いててオーバーライド先をルートと見立てたパス指定ができるなら、そもそも子のフォルダいらない説も出てきましたがまだ試してないです。
<img width="828" alt="スクリーンショット 2024-09-24 18 59 16" src="https://github.com/user-attachments/assets/e69f20a2-3ebd-45ee-8d03-4958129f64ca">

**Comment by lilxyzw** [comment]
ん……？メニューを入れ子にすると自動で親オブジェクトのMenuFolderがメニューの親フォルダになるはずですがならない感じですか……？

**Comment by lilxyzw** [comment]
こちらでも確認できました。親フォルダがModular Avatarでオーバーライドされている場合のみメニューが生成されなくなるようです。こちらバグなので修正します。
