### ISSUE TITLE
v1.2.0 and up breaks MA menus

### ISSUE THREAD

**Issue by Dartv** [lilxyzw/lilycalInventory#120]
When upgrading from 1.1.1 to 1.2.0 or 1.3.0 my MA menus become empty.

This is how I have it set up:
![](https://i.gyazo.com/c88608e40a3535b72ae5350b55d4af5a.png)
![](https://i.gyazo.com/374273f3920e691061c579be3dae0593.png)
![](https://i.gyazo.com/55c35aa3a8885d8122cb373011e37e88.png)
"Clothes" menu is there, but when I open it it's empty. This is working on 1.1.1.

MA version is latest - 1.9.16.

**Comment by lilxyzw** [comment]
This is a known bug, because Modular Avatar doesn't support menus edited by other tools. There's nothing lilycalInventory can do about this, so I've submitted a fix request to Modular Avatar.
https://github.com/bdunderscore/modular-avatar/issues/1173
