### ISSUE TITLE
MA導入環境でLI CostumeChangerを使用するとVRCExpressionsMenu uses a parameter that is not defined.が発生

### ISSUE THREAD

**Issue by gokoukotori** [lilxyzw/lilycalInventory#122]
lilycalInventory:1.3.0
Modular Avatar:1.9.16
MA共存環境においてLI CostumeChangerを使うとVRCExpressionsMenu uses a parameter that is not defined.が発生する。
MA Parametersコンポーネントを追加してLI CostumeChangerで使用するパラメータを記載すると解消する。
lilycalInventoryが1.2.0のときは発生しなかったため念の為記載します。

**Comment by lilxyzw** [comment]
1.2.0でIntパラメーターの圧縮が実装されて、LI CostumeChangerが生成するパラメーターがIntではなく複数のBoolに分割されました。lilycalInventoryが生成するパラメーターを外部から使用することは想定していないため、ConstumeChangerが生成するパラメーターをlilycalInventory外から操作・利用している場合はエラーになると思われます。今後もパラメーター周りは変更されうるため外部からの利用は推奨されません。

**Comment by gokoukotori** [comment]
追記
以下のような階層でMAコンポーネント及びLI CostumeChangerを使用すると発生するようです。
なおConstumeChangerが生成するパラメーターは外部から一切操作しておりません。
ルート（使用コンポーネント：MA Menu Installer、MA Menu Group）
　└CostumeChanger用Object（使用コンポーネント：LI CostumeChanger、MA Menu Item）
　　　└LICostumeChanger用メニュー（使用コンポーネント：MA Menu Item）

LI CostumeChangerの設定
<img width="381" alt="image" src="https://github.com/user-attachments/assets/77f812fc-c279-492d-b0eb-ae1cfd2119eb">
