### ISSUE TITLE
Layer priority

### ISSUE THREAD

**Issue by Dartv** [lilxyzw/lilycalInventory#124]
Sometimes it is necessary to have a layer have higher priority to override things, especially those generated by other tools like MA.
MA has priority feature and lilycalinventory should too.
!![](https://i.gyazo.com/dc654da3bb3337725330bbf6f0422853.png)

**Comment by lilxyzw** [comment]
lilycalInventory uses Direct Blend Tree, so all layers are one. Since it is not possible to set a priority for each component, is it okay to implement it so that all components in lilycalInventory have the same priority?

**Comment by Dartv** [comment]
There's a setting to not use a blend tree, isn't there? Or at least a global setting for a blend tree layer to be able to override MA layers.

**Comment by lilxyzw** [comment]
I created a component that adds lilycalInventory to avatar as MA Merge Animator, this will be added in the next version.
![image](https://github.com/user-attachments/assets/27a8d321-6ffa-4eaa-8685-52509415a38c)
