### ISSUE TITLE
MaterialModifierより前にItemTogglerが初期値を作成します

### ISSUE THREAD

**Issue by kvehub** [lilxyzw/lilycalInventory#128]
LI MaterialModifierでマテリアルのプロパティを統一する設定をしましたが、
上で設定したプロパティをLI ItemTogglerで操作する設定をするとItemTogglerのAnimationClip初期値はMaterialModifier設定前の状態で作成されます
マテリアルを意図する設定に統一して操作できないためissueを作成します

Non-Destructive Modular Framework 1.5.0-rc.9
Modular Avatar 1.10.0-rc.8
lilycalInventory 1.3.1

**Comment by lilxyzw** [comment]
ItemToggler（メニュー系コンポーネント）でアニメーションを生成
↓
ModularAvatarでオブジェクトが移動されつつアニメーションのパスを修正＆AnimatorControllerを統合
↓
MaterialModifierで（ModularAvatarで追加されたアニメーション内のマテリアルを含む）全マテリアルのプロパティを変更

という処理順にしないとうまく動作しないため仕様通りではありますが、なんとかしてみました。
