### ISSUE TITLE
Could ”Parent Folder“ support VRChat Expressions Menu file?

### ISSUE THREAD

**Issue by MilkKira** [lilxyzw/lilycalInventory#132]
Although LI Menu Folder can be installed in the default VRC Expressions Menu Files, it is not entirely necessary to use lilycalInventory to create menus in subsequent menu creation.

For some options, it is preferred to use the native files for sorting and categorising.

These native menu files cannot be merged into the LI Menu Folder, which may lead to confusion and cumbersomeness.

If possible, can Parent Folder support native VRC Expressions Menu?

**Comment by lilxyzw** [comment]
Do you want to create a lilycalInventory menu in an existing menu? If the menu directory set in lilycalInventory matches the avatar's menu, the lilycalInventory menu will be generated in the avatar's menu.

**Comment by MilkKira** [comment]
![image](https://github.com/user-attachments/assets/375f2d90-1189-43c3-b49b-56e2d2863541)

Some of the decorations that use MA will be installed to the Root Menu using the Menu Installer.

What I mean is that I want this menu to be installed to the menu generated by lilycalInventory.

Or the MA menu is installed into an existing submenu and the menu generated by lilycalInventory is installed into the same existing submenu.

**Comment by MilkKira** [comment]
![image](https://github.com/user-attachments/assets/f9eb9dea-b1b2-4698-b02b-12da4837111f)
You mean if name matched,it will install that existing sub menu?

**Comment by MilkKira** [comment]
Sloved >w<
