### ISSUE TITLE
LI Comment上でEditor Languageを変更すると、"メッセージの種類"の選択欄が表示されなくなる

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#19]
### 現象
- LI CommentのInspector表示中に、LI Comment上のプルダウンからEditor Languageを変更すると、メッセージ編集時の「メッセージの種類」の選択欄が出なくなる
- LI Comment以外のLIコンポーネントで言語を変更しても本現象は発生しない
- 言語の変更を行うタイミングが編集中であるかどうかに関わらず、本現象は発生する
- 別のObjectを選択するなどしてInspectorを再表示すると再び「メッセージの種類」の欄が表示されるようになる

### 環境
Unity: 2019.4.31f1
LI: 0.3.4

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。devブランチにて修正を行ったので次のリリースにて反映いたします。
