### ISSUE TITLE
初期状態がdisableのオブジェクトにLI Propが付いている場合、そのオブジェクトのメニューとアニメーションが生成されない

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#21]
初期状態がオフ状態になっているGameObjectにLI Propが付いている場合、それをオンにするメニューとアニメーションが生成されることが予想されますが、実際には何も生成されません。

Unity: 2019.4.31f1
LI: 0.3.4

**Comment by lilxyzw** [comment]
前回のアップデートで非アクティブのオブジェクトについているコンポーネントを処理対象から外したことが原因だったため一旦仕様を差し戻すことで対処しました。次のリリースでmainブランチに修正を反映いたします。
