### ISSUE TITLE
親子でLI PropやAutoDresser等が付いている場合に、親にLI MenuFolderを付けられるようにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#24]
## 状況
衣装や小物を切り替えたいが、その中にも切り替えられるパーツがあるような場合は、親子でLI PropやAutoDresserが付くことになります。
この際、子の切り替えをメニューに分離するために、親にMenuFolderを付けようとすると
`Can't add 'MenuFolder' to ** because a 'Prop' is already added to the game object!
A GameObject can only contain one 'MenuBaseComponent' component.`と言われてしまいます。
別のGameObjectにLI MenuFolderを付け、オーバーライドで指定することにより回避は可能ですが、直接付けられる方が直感的かもしれません。
(親が衣装(AutoDresser)の場合は、実用上はメニューの階層が別になることが予想されるため、必ずオーバーライドすることになる気はします。そのため、親がPropの場合を主に考慮すれば良いのかもしれません?)

**Comment by lilxyzw** [comment]
MenuFolderコンポーネントのみ重複を許可するように変更を加えました。こちらの変更は次のリリースでmainブランチにも反映いたします。
