### ISSUE TITLE
AutoDresserとPropをCostumeChangerとItemTogglerに変換するやつ

### ISSUE THREAD

**Issue by lilxyzw** [lilxyzw/lilycalInventory#27]

**Comment by lilxyzw** [comment]
あとから衣装を追加するときCostumeChanger経由になって困りそう？

**Comment by c-colloid** [comment]
個人的にはAutoDresserをCostumeChangerの排他制御に加えられるような仕組みが欲しい所ですね

変換機能よりも、
AutoDresser+CostumeChangerがある場合
AutoDresserを読み込んで、CostumeChangerが継承+全体的な管理

とする仕組みの方が後から衣装を追加した時にもAutoDresserがありさえすれば勝手にコスチュームの切替が追加されていく形になって分かりやすいのではないでしょうか
