### ISSUE TITLE
切り替え対象のオブジェクトを纏めて追加出来るように等、UI改善案

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#28]
幾つか思いついた改善案を投げてみます。参考画像はAutoDresserですが、恐らく他のコンポーネントでも同様です。

1. "オブジェクトのオンオフ"に物を追加したい場合、現在は1つずつ+ボタンで枠を追加してからセットする必要があります。
これを、複数オブジェクトが纏めてドラッグすることで、(0個の状態からでも)纏めて増やせるようになっていると便利です。
現状の並び替え可能なUIとは微妙に共存が難しいかもしれません。(UI Elementsでの実装例を見た記憶が無いため)
("マテリアルの置き換え"等のRendererを入れる場所でも、つまりHierarchyから纏めて入れられるものであれば全て同様かも…?)

2. "BlendShapeの切り替え"について、"メッシュ"の中には"切り替えるBlendShapeと値"しかなく、"メッシュ"自体にもfoldoutが付いているため、"切り替えるBlendShapeと値"の方にはfoldoutが不要なように思います。
現状でBlendShapeの切り替え対象を増やす場合、メッシュをセットし、foldoutを開き、"切り替えるBlendShapeと値"のfoldoutを更に開いてから編集する必要があり、恐らく少し不便です。

3. "マテリアルの置き換え"の中の、各メッシュごとにfoldoutがありますが、これは不要なように思います。
メッシュとマテリアル1つずつしか幅を取らないため、増える手間の方が大きそうな気がします。

### 現在(0.3.5)のUI
![image](https://github.com/lilxyzw/lilycalInventory/assets/61457993/3afdc9e4-1567-48b2-b980-c9fd3baf907b)

**Comment by Sayamame-beans** [comment]
参考までに: AAOでは追加する用のスロットが生えていて、複数追加にも対応しています。(非UI Elementsです。[例](https://vpm.anatawa12.com/avatar-optimizer/ja/docs/reference/merge-skinned-mesh/#settings))。UdonSharpでは配列のfoldoutの部分(ラベルの部分)にD&Dすると複数入ります。

**Comment by lilxyzw** [comment]
こちらの改善案は一通り実装したのでcloseします。もし他に改善点が見つかったら新たにissueをお願いします。
