### ISSUE TITLE
changelogが欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#32]
まだベータ版なのでまあ無くても…という感じもありますが、やはり気になるのであると嬉しいかもしれません。
雰囲気な感じで良ければ、リリース時のノートから文章を持ってきてPRします!

**Comment by lilxyzw** [comment]
ありがとうございます
リリース時のメモは残っているのでこちらでchangelogを書いておきます

**Comment by Sayamame-beans** [comment]
ありがとうございます🙏
