### ISSUE TITLE
ExpressionParametersの上限・消費量・残量を見れるようにする

### ISSUE THREAD

**Issue by lilxyzw** [lilxyzw/lilycalInventory#33]

**Comment by Sayamame-beans** [comment]
Related?: https://github.com/bdunderscore/modular-avatar/issues/424
MAや他のツールが生成するパラメーターの使用量が見えない以上、正確な消費量が見えないのは少し気がかりですね…
MAかNDMF側にもissueが必要でしょうか…?

**Comment by lilxyzw** [comment]
MAについてはこちら側で対応しました。
ツールごとに個別に対応していく必要があって大変なのでNDMFにapiがあると嬉しいのはそうかも……？

**Comment by lilxyzw** [comment]
lilycalInventory側での対応は終わったのでcloseします。もしNDMF側やMA側でAPIが追加されたら適宜対応します。
