### ISSUE TITLE
各メニューの有効化時/無効化時に任意のアニメーションを再生する機能、またはオブジェクトの出現/消失アニメーションの生成

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#46]
一部に需要があるみたいなので投稿しておきます。(私個人としては、任意のアニメーションが利用出来る方の嬉しさは分かっていません)

オブジェクト切り替えの出現/消失アニメーションについては、AutoDresserとPorpが切り替えを担当する都合上、出現/消失パターンをツール側に組み込む形でないと適用が難しそうだと思っています。

いずれにしろ、priorityはlowだと考えています。

**Comment by lilxyzw** [comment]
有料版の機能として追加する可能性はありますが、今のところ実装予定はないです。
