### ISSUE TITLE
パラメータをまとめて制御する機能が欲しい

### ISSUE THREAD

**Issue by kvehub** [lilxyzw/lilycalInventory#56]
CostumeChangerまたは追加のコンポーネントで
・パラメータ名
・ItemToggler、Propの設定されたオブジェクト
をセットしてパラメータをまとめてオンオフできると便利かなと思いました

**Comment by lilxyzw** [comment]
次回バージョンにてLI Presetというコンポーネントが追加されます。操作対象のコンポーネントと値を指定することで、VRChat上のメニューから複数パラメーターを一括で指定した値にセットできます。
![image](https://github.com/user-attachments/assets/60514027-b9a5-40bf-a30c-ad6a3de6d346)
