### ISSUE TITLE
”デフォルト以外”のコスチュームの一部をItemToggler/Propで「脱げる」ようにしたい

### ISSUE THREAD

**Issue by c-colloid** [lilxyzw/lilycalInventory#60]
現状の設計ですと”デフォルト以外”のコスチュームの一部をItemToggler/Propで制御したい場合

1．Hierarchy上でオフにしているオブジェクトはデフォルトが脱いだ状態になってしまいコスチュームチェンジするとItemToggler/Propを設定した服が脱げてしまう
2．デフォルトを着た状態にしようとするとすべてのオブジェクトをオン状態で編集する必要があり、見た目が悪く管理もしづらい
3．この中間の解決策としてオブジェクトオフ+ItemTogglerでチェックを外すというのを試したが、するとオンオフの切替が働かない

つまり、アバターの中に階層が無く複数コスチュームを設定したアバターの場合、
ItemToggler/Propを使って「着せる」設定しかできない
という問題があり初回アップロード時に事故が起こるので改善が必要だと思います

**Comment by Sayamame-beans** [comment]
恐らく、排他的に切り替えたいものはAutoDresser、個別に切り替えたいものはPropという区分だと思うので、階層化されていない状態で非デフォルトコスチュームのパーツが並んでいる(排他で有効な間には個別に切り替えたいが、階層になっていないので排他での切り替えに個別の切り替えが巻き込まれてくれない)というケースはLIの思想的に想定外のケースな気がしています…?
(非prefabであれば親として空オブジェクトを挟むことも出来るとは思いますが…)

**Comment by Sayamame-beans** [comment]
考えてみたのですが、親となる排他切り替え(AutoDresser等)によって制御される、子の切り替えオブジェクト(Prop等)という関係を認識出来れば実現出来るかもしれません…?

1. 排他切り替えしたいオブジェクトAと、個別切り替えしたいオブジェクトBがあるとし、AとBは同一階層にあるとします。
3. Aの拡張設定として、BをAの切り替えに合わせて制御するようなオプションを追加します。(AをオフにしたらBが同時にオフになるように、AをオンにしたらBの初期状態(後述)になるように)
4. Aのプレビュー時は、Bも同時にプレビューされるようにします。この時、Bは初期状態(後述)にします。
5. Bのプレビュー時は、Aを有効にし、Bを初期状態(後述)から切り替えた後の状態にします。

ここで、現在の仕様ではBの初期状態がHierarchy上で定義出来ない(AをオフにしているとBも一緒にオフにされる/したいため)ことに気付きます。
そのため、BのProp設定側で初期状態を設定出来るようにする必要が生じます。
逆に言えば、BのProp設定側で、Aの排他制御によって同時に制御され、Aが有効になっている間のBの初期状態が定義出来れば、後はこれまでのPropと同様になると推測します。

残るは…これに相当するアニメーションが生成出来るかどうか…?

**Comment by lilxyzw** [comment]
ビルド時にItemTogglerに設定したアクティブ状態の逆になるようにオブジェクトのアクティブ状態を上書きするような形で組んでみます。
Edit Mode上のアクティブ状態と異なる見た目になり事故が発生する可能性も考えられるので、そこは別途ドキュメントやヘルプボックスなどに記述して対応します。

**Comment by c-colloid** [comment]
https://github.com/lilxyzw/lilycalInventory/assets/28706700/8bab87a1-7016-4fd2-8680-5607bc8a07ce

一応、問題点が伝わるように具体例の動画を撮ってきました
・デフォルト衣装のパンツとアンダーシャツはデフォでオフ
・コスチュームチェンジで
　0=>デフォルト衣装
　1=>コニカ衣装
　2=>両方を脱いで下着のみ
の設定
・アンダーシャツは
> 1．Hierarchy上でオフにしているオブジェクトはデフォルトが脱いだ状態になってしまいコスチュームチェンジするとItemToggler/Propを設定した服が脱げてしまう

の設定
・パンツは
> 3．この中間の解決策としてオブジェクトオフ+ItemTogglerでチェックを外すというのを試したが、するとオンオフの切替が働かない

を設定

* 結果

下着のみに着替えるとアンダーシャツが脱げた状態から始まる
パンツは着た状態だが、切り替えが死んでいる

**Comment by nekobako** [comment]
コスチュームを下着に切り替えたときの挙動について、

- colloid さんが issue を立てた時点
  - アンダーシャツ: メニューが無効なら非アクティブになり、メニューが有効ならアクティブになる
  - パンツ: メニューの状態に関わらず常にアクティブになる
  - → colloid さんの動画の通りの挙動
- lil さんが修正を入れた時点 (b08b19f)
  - アンダーシャツ: メニューが無効なら非アクティブになり、メニューが有効ならアクティブになる
  - パンツ: メニューが無効なら非アクティブになり、メニューが有効ならアクティブになる
  - → コスチュームを下着に切り替える前にアンダーシャツとパンツのメニューを有効にしておかなければ全裸になる
- 私が別件の対応を入れた時点 (e506bee)
  - アンダーシャツ: メニューが無効なら非アクティブになり、メニューが有効ならアクティブになる
  - パンツ: メニューが無効ならアクティブになり、メニューが有効なら非アクティブになる
  - → アンダーシャツをパンツと同じ設定 (ItemToggler で「オフにする」を選択) にすれば意図した挙動になるはず
  - → だったのですが、バグを混入してしまったので #74 のマージ待ちです…

という状況です。
