### ISSUE TITLE
CostumeChanger の 0 番目は何も指定できるべきではないかも

### ISSUE THREAD

**Issue by nekobako** [lilxyzw/lilycalInventory#68]
ItemToggler は、メニューを操作していないときはアバターがビルド時の状態となり、メニューを操作したときにアバターの状態が変化するのに対し、CostumeChanger は全てのメニューに対して状態を指定できるため、デフォルトだと思っていた状態がデフォルトでないということが起こりうるかなと思いました。

オブジェクトのオンオフについてはビルド時に 0 番目のコスチュームに合わせる処理がありますが、オブジェクトのオンオフ以外はそのままになるという点と、プレイモードに入ったら勝手に状態が変わるという点で混乱が生じそうですので、ビルド時の状態を 0 番目の衣装として扱い、ユーザーが指定できるのは 1 番目以降という仕様とするならば、ItemToggler とも挙動が一致していて分かりやすいのではないかと思います。

ただ、アイコンやメニュー名は 0 番目から設定できる必要があるので、Inspector では 0 番目のコスチュームの部分がグレーアウトして表示されるとよいのではないかと思っています。

**Comment by nekobako** [comment]
> 0 番目のコスチュームの部分がグレーアウトして表示されるとよいのではないか

ItemToggler に関してもメニューがオフのときの状態をグレーアウトして表示できるととても分かりやすくなりそうです。

- ItemToggler 
  - オフのとき
    - オブジェクトのオンオフ (グレーアウトでデフォルト状態を表示)
    - …
  - オンのとき
    - オブジェクトのオンオフ (設定可能)
    - …
- CostumeChanger
  - メニュー名
    - オブジェクトのオンオフ (グレーアウトでデフォルト状態を表示)
    - …
  - メニュー名
    - オブジェクトのオンオフ (設定可能)
    - …
  - メニュー名
    - オブジェクトのオンオフ (設定可能)
    - …

こうなってくると ItemToggler は実質コスチュームが 2 つしかない CostumeChanger なので、生成するパラメータの型とフォルダを生成するかどうかが異なるだけで内部的には共通化できたりしないかなと思っています。(が、話が大きくなりすぎな気がするのでこれはまた別の話かも)

**Comment by nekobako** [comment]
SmoothChanger に関しても、LightChanger プレハブでパペット設定値を 0% - 2% - 100% のように設定している箇所がいい感じにならないかなと少し思ってます。
(0% は強制デフォルト状態で、設定できるのは 1% からなど)

**Comment by lilxyzw** [comment]
例えば、

- 0番目
  - アバターデフォルト衣装の上着をオン
  - アバターデフォルト衣装の靴をオン
- 2番目
  - 別の衣装Aのルートをオン
- 3番め
  - 別の衣装Bのルートをオン

というように設定した場合、内部的に

- 0番目
  - アバターデフォルト衣装の上着をオン
  - アバターデフォルト衣装の靴をオン
  - 別の衣装Aのルートをオフ
  - 別の衣装Bのルートをオフ
- 2番目
  - アバターデフォルト衣装の上着をオフ
  - アバターデフォルト衣装の靴をオフ
  - 別の衣装Aのルートをオン
  - 別の衣装Bのルートをオフ
- 3番目
  - アバターデフォルト衣装の上着をオフ
  - アバターデフォルト衣装の靴をオフ
  - 別の衣装Aのルートをオフ
  - 別の衣装Bのルートをオン

に変換されるようになっています。仮に0番目に何も指定できなくした場合、

- どのメッシュがアバターデフォルト衣装か判定できない（表示されている全メッシュを消すようにすると体が巻き込まれる）
- 明示的に2番目・3番目にデフォルト衣装をオフにする設定を追加するのは手間
- 手間を避けるために他にプロパティを作成してそこで指定できるようにする場合かえってわかりづらくなってしまう

と考えられるため0番目もあったほうが良いのではないかと思います。

**Comment by nekobako** [comment]
> 明示的に2番目・3番目にデフォルト衣装をオフにする設定を追加するのは手間

たしかにそうですね…！
ItemToggler の方は 2 状態しかないからこその指定方法であって、無理に合わせる必要がないと理解しました。
Close します。
