### ISSUE TITLE
NDMFに対応していることについてドキュメントに記載して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#80]
lilycalInventoryはNDMF対応でありながら、NDMFが無い場合には独立して動作することも可能なように設計されていると聞きました。
> NDMFがあればNDMFプラグインとして、なければ普通にIVRCSDKPreprocessAvatarCallbackでやってます
https://misskey.niri.la/notes/9wrknhlskv

しかし、その旨はドキュメントやBoothページに記載されておらず、一部のユーザーに誤解が発生しているようです。
そのため、NDMFに対応しているけれど必須ではないという旨をドキュメントに記載して頂けると良さそうです。

**Comment by Sayamame-beans** [comment]
```
lilycalInventoryは単体でも動作するため、NDMFの導入は必須ではありません。
ですが、プロジェクトにNDMFが導入されている場合はNDMFを使用して動作するようになっているため、NDMFを使用している他の非破壊改変ツールも同時に使用することができます！
```

みたいな感じでしょうか…
少し"NDMF"の書かれる数が多い感じがするのと、文章を分かりやすくかつ短くするのが難しいです…

**Comment by lilxyzw** [comment]
こちらで書いてみます

**Comment by Sayamame-beans** [comment]
ありがとうございます🙏

**Comment by Sayamame-beans** [comment]
Booth側の説明分にも同様の文言を追加しておいていただけると更に良さそうです! 🙏
