### ISSUE TITLE
"マテリアルのプロパティ操作"でマテリアル単位の変更を扱えるように

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilycalInventory#81]
LI 1.0.0現在、マテリアルの置き換えはマテリアル単位で行うことが出来ますが、マテリアルのプロパティ操作操作はメッシュ単位の設定になっているようです。
しかしながら、マテリアルプロパティにはマテリアル単位で行える変更もあったと思うので、メッシュ全体に反映されるものを操作したいケースと、マテリアル単位で反映されるもの操作したいケースは両方ある可能性があります。

これを両立するUIを考えるのは難しいですが…可能であれば、マテリアル単位の操作も出来るようになると良いと思います!

**Comment by lilxyzw** [comment]
AnimationClipではマテリアルの差し替えはスロットごとにできるけどプロパティ操作はメッシュ単位にしかできないはず……？

**Comment by Sayamame-beans** [comment]
そうかも…(何かと勘違いしたかもしれません)(確認中)

**Comment by Sayamame-beans** [comment]
勘違いっぽいので閉じます、すみません
