### ISSUE TITLE
LI Propにて、オブジェクトのオンオフに追加したリストが消えてしまう

### ISSUE THREAD

**Issue by S0iRu** [lilxyzw/lilycalInventory#86]
以下2パターンの操作において、[LI Prop]の[オブジェクトのオンオフ]に追加したリストが勝手に消えてしまうのを確認しています。

・[LI Prop]の[オブジェクトのオンオフ]で追加
　→[オンにする/オフにする]のプルダウンを選択する
　→リストが空になる

・"オン"にしたいオブジェクトに[LI Prop]を追加
　→[オブジェクトのオンオフ]に、同時に"オフ"にしたいオブジェクトを設定
　→"オン"にしたいオブジェクトとは別のオブジェクトを選択する
　→リストが空になる

**Comment by S0iRu** [comment]
Unityバージョン：2022.3.22f1
lilycalInventoryバージョン：1.0.0

**Comment by S0iRu** [comment]
上記コメント記載後に引き続き作業していたところ、
2つ目のパターンにおいて、今度はリストを消しても復活するようになりました。
推測ですが何らかのタイミングで情報が残っていそうです。

**Comment by lilxyzw** [comment]
原因を特定できないのと他に例を見ないので、こちらでも同様の問題が発生した場合に修正を行います。
