### ISSUE TITLE
AAOから未知のコンポーネントと言われてしまう？

### ISSUE THREAD

**Issue by KisaragiEffective** [lilxyzw/lilycalInventory#90]
per https://misskey.niri.la/notes/9wulgq2h0x

**Comment by Sayamame-beans** [comment]
そのタイミングではLIのコンポーネントは消えている想定だと思うので、LIのコンポーネントが残るなんらかのバグパターンだと思っています

**Comment by KisaragiEffective** [comment]
won't fix: local environment setup defect per https://misskey.niri.la/notes/9wupiwts3s
