### ISSUE TITLE
メニューを生成しないオプション

### ISSUE THREAD

**Issue by ni1chigo2115** [lilxyzw/lilycalInventory#91]
事前にアバター側で設定された変数に同期させたい場合などに、二重にメニューを作るのを防ぐためにメニューを生成しないオプションが欲しいです。
（先に胸のサイズ変更というオプションがあったとして、衣装側で同じ変数を共有するメニューを作ってしまうと二重に胸サイズ変更オプションが生成されてスマートではない）

**Comment by lilxyzw** [comment]
アバターと衣装の胸サイズの連動についてはこちら[MA Blendshape Sync](https://modular-avatar.nadena.dev/ja/docs/reference/blendshape-sync)では実現できない感じでしょうか……？

**Comment by ni1chigo2115** [comment]
こういうのが来ると連動できなくなって自分で設定する必要が出てくるので・・・（Betaは未使用です）
アバターの胸のサイズと連動しないシェイプキーはどうしても自分で実装する必要がでてくる
後は元のアニメーターを消して実際の胸変更の挙動をコンポネート側で行うとしても、メニューだけ先置きしておきたいとかもあったりします
![20240901_breast](https://github.com/user-attachments/assets/4a05bd0c-dd2a-4a44-a785-5d2307f6b7f7)

**Comment by lilxyzw** [comment]
これはlilycalInventoryよりModular Avatarに機能を生やしたほうが他の着せ替えツールにも利用できて有益なので、Modular Avatarの方にも意見を出してみます。

https://github.com/bdunderscore/modular-avatar/issues/396

**Comment by lilxyzw** [comment]
まだこの問題に対応する機能が実装されていないのでアバター本体のデータの改変が必要になってしまいますが、以下の2パターンどちらかで対応できるかと思われます。

- アバター側の胸サイズ変更アニメーションに衣装のBlendShapeを操作するキーを追加する
- アバター側の胸サイズ変更オプションを削除してLI SmoothChangerだけにする
