### ISSUE TITLE
About parent constraint on off

### ISSUE THREAD

**Issue by Itukii** [lilxyzw/lilycalInventory#94]
I'm going to make a toggle about komano's hood.
but i didn't see any about i can change in ItemToggle.
I try to insert animation clip
but it seems didnt work. or something i set mistake.
If you can tell me how to do it will be helpful.
![image](https://github.com/user-attachments/assets/4d416825-6e3e-415e-939b-a6c54fee71e3)
![image](https://github.com/user-attachments/assets/365cc134-9eaa-41cb-a7f8-976aee65c8bd)

**Comment by lilxyzw** [comment]
It was a bug that the menu was not generated when only AnimationClip was set. It has been fixed, so please wait for the next version.
