### ISSUE TITLE
in mmd world autodresser physbone can not works

### ISSUE THREAD

**Issue by Itukii** [lilxyzw/lilycalInventory#95]
dress any two clothes, 
choose the default off one, 
into a random mmd world and play it, 
physbone can not works.

https://github.com/user-attachments/assets/1360159e-86a9-4744-9a7b-853f2d4da887

**Comment by lilxyzw** [comment]
I just tested it and PhysBone worked. Here are some possible causes:
- Is PhysBone or its game object inactive or EditorOnly?
- Is the object animated by another AnimationClip?
- Does PhysBone work on Unity?
- Does PhysBone work if you don't use lilycalInventory?
- Is it conflicting with another tool?

**Comment by Itukii** [comment]
- Is PhysBone or its game object inactive or EditorOnly?
i think is all in untagged.
- Is the object animated by another AnimationClip?
no, im using the body prefab and add new clothes
- Does PhysBone work on Unity?
yes
- Does PhysBone work if you don't use lilycalInventory?
if i upload the avatar with one of the clothes is yes.
- Is it conflicting with another tool?
im using these tools.
![image](https://github.com/user-attachments/assets/dfb1bdcb-0dd9-44c1-b38a-2090e6ca8874)

https://github.com/user-attachments/assets/b98265a9-aabf-4fb8-a0dc-5eb0a939d3d1

**Comment by Itukii** [comment]
if i check this toggle on then upload ,only the serafuku physbone works.
![image](https://github.com/user-attachments/assets/85178dfb-483c-49b3-86db-2d28416a1138)

**Comment by lilxyzw** [comment]
Thanks for checking. According to the world description, the weights of the first and second layers of the AnimatorController are set to 0. In other words, you may be able to avoid the problem by creating layers 0, 1, and 2 and not generating the lilycalInventory layer in these layers.

**Comment by Itukii** [comment]
![image](https://github.com/user-attachments/assets/70c0e5ef-f74a-4ee4-8796-44889233ffb4)
this is the fx layer . 
can you tell me what should i do with lilycalInventory.
thanks very much.

**Comment by lilxyzw** [comment]
Hmm...I don't have this bug so I can't identify the cause...

**Comment by lilxyzw** [comment]
I can't fix it because I can't identify the cause. I will fix this issue if I encounter a similar problem.
