### ISSUE TITLE
LI Propがプレビューでは動作するが、VRChat内では動作しない

### ISSUE THREAD

**Issue by brmA8864** [lilxyzw/lilycalInventory#99]
LIPropを利用して帽子とヘッドドレスの切り替えの方を行いたいと思い、LI Propをヘッドドレスの方に付与し、複数オブジェクトで他の小物をおんにするように設定しました。
![image](https://github.com/user-attachments/assets/3eb9751e-0cdc-4faa-806a-e8052ab53e48)

プレビュー上では問題なく切り替わるのですが、VRChat上での切り替えが行われず、ご助力お願いしたいです

**Comment by lilxyzw** [comment]
動作しないといっても様々な状況が推測できるので考えられるすべてのパターンを上げていきます。

## メニューが生成されない場合
- コンポーネント自体のチェックボックスがオフになっていないかを確認
![image](https://github.com/user-attachments/assets/977f8e6c-e3ce-40d3-beb5-c0d0bdb70118)
- メニューがついたオブジェクト自体がEditorOnlyになっていないかを確認
![image](https://github.com/user-attachments/assets/da516b58-6dc2-4c57-bc91-0c20118c868c)
- エラーログが出ていないかを確認→[参考](https://note.com/watahumi_mina/n/nb3774c24fc7b)

## メニューを操作しても操作対象のオブジェクトが表示されない場合
- 操作対象がEditorOnlyになっていないかを確認
- 操作対象が他のAnimationClipやコンポーネントから操作されていないかを確認
- 操作対象のBoundsやRootBoneが適切か確認→[参考サイト](https://kan-kikuchi.hatenablog.com/entry/UnityMaskMan_Massage)
- エラーログが出ていないかを確認→[参考](https://note.com/watahumi_mina/n/nb3774c24fc7b)
- そもそもエディタ上で正しく動作するかを確認
  →[NDMF（Modular Avatarなどの前提ツール）](https://modular-avatar.nadena.dev/ja/docs/intro)とGesture Managerが入った状態であればPlay ModeのときにUnity上で動作確認ができます

**Comment by brmA8864** [comment]
@lilxyzw
ご回答ありがとうございます


> メニューが生成されない場合
こちらに関しては生成自体はされるので問題なさそうです。

NDMFの方を入れて確認したところメニュー自体は表示されるのですが、Playを押した際に追加しているはずのComponentであるLI Propが消えてしまっていました、こちらが原因の可能性ありますか？

![Animation](https://github.com/user-attachments/assets/8bfaab73-ef75-4853-9c00-ac46d9905d25)

**Comment by lilxyzw** [comment]
コンポーネントが消えるのは正しい状態です。（VRChatでは独自のコンポーネントが使えないので、実際に使うときにはアニメーションやパラメーターに変換されるようになっています）
Unity上でGestureManagerを使った場合はオブジェクトのオンオフは切り替えられますか……？

**Comment by brmA8864** [comment]
@lilxyzw なるほど、そうなのですね。

GestureManagerを使ったオンオフの切り替えはできないです。
VRC内で行ったときと同じでオンでもオフでもオブジェクトの状態が変わらないです…

**Comment by brmA8864** [comment]
![Animation](https://github.com/user-attachments/assets/8848b1ba-37b3-4555-b624-9c8c4813efe9)

**Comment by lilxyzw** [comment]
原因を特定できないのと他に例を見ないので、こちらでも同様の問題が発生した場合に修正を行います。
